name: deprem_destek
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  firebase_core: 2.4.1
  firebase_auth: 4.2.5
  cloud_firestore: 4.3.1
  flutter_bloc: 8.1.1
  collection:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  very_good_analysis: 3.1.0
  freezed: 2.3.2
  build_runner: 2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Book.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-MediumItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 700
          style: italic
